-- Initial migration for BlogPost table
-- This file is auto-generated by Prisma migrate command
-- Run with: npx prisma migrate dev --name init

CREATE TABLE IF NOT EXISTS "BlogPost" (
  "id" SERIAL NOT NULL PRIMARY KEY,
  "title" VARCHAR(255) NOT NULL,
  "slug" VARCHAR(255) NOT NULL UNIQUE,
  "excerpt" VARCHAR(512) NOT NULL,
  "content" TEXT NOT NULL,
  "coverImage" VARCHAR(512),
  "category" VARCHAR(255) NOT NULL DEFAULT 'Financial Planning',
  "readTime" VARCHAR(255) NOT NULL DEFAULT '5 min read',
  "publishedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX "BlogPost_slug_idx" ON "BlogPost"("slug");
CREATE INDEX "BlogPost_publishedAt_idx" ON "BlogPost"("publishedAt");
