CREATE DATABASE IF NOT EXISTS levplan_blog CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE levplan_blog;

CREATE TABLE IF NOT EXISTS BlogPost (
  id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  excerpt VARCHAR(512) NOT NULL,
  content LONGTEXT NOT NULL,
  coverImage VARCHAR(512) NULL,
  publishedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id)
);
